Янтимиров Тимур, Вариант 10(uniq)
h31/ProgrammingLabSummer2020Task2 pull request #6
Opened 2020-03-31 18:19 UTC by yantimirov-timur

2020-04-09 10:33 UTC, Artyom-boop commented on src/test/java/com/example/project/UniqueTest.java
> +    void equalsIgnoreCase() throws IOException {
Кажется, ты неправильно понял условие
![1234](https://user-images.githubusercontent.com/54851774/78886149-6b14ce80-7a66-11ea-9338-af76ebe9b98d.jpg)

2020-04-09 10:34 UTC, Artyom-boop commented on src/test/java/com/example/project/UniqueTest.java
> +    void equalsIgnoreSomeCharsString() throws IOException {
Аналогично с условием
![12345](https://user-images.githubusercontent.com/54851774/78886389-c8108480-7a66-11ea-9930-368f66c5b414.jpg)

2020-04-09 12:48 UTC, h31 requested changes

2020-04-09 12:48 UTC, h31 commented on pom.xml
> +			<dependency>
Лишние пробелы

2020-04-09 12:48 UTC, h31 commented on src/main/java/com/example/utility/UniqueLauncher.java
> +        else if (Arrays.asList(args).contains("-s")) { //опция -s имеет параметр типа int,поэтому проверка на существование в виде листа
Я думаю, это можно сделать каким-то более очевидным способом. Например, назначить переменной `num` какое-нибудь значение по умолчанию, по которому определять, записывалось ли в это поле что-нибудь другое

2020-04-09 12:48 UTC, h31 commented on src/main/java/com/example/utility/Unique.java
> +            Scanner fileInput = new Scanner(new File(input));
Если нужно считать файл построчно, то вместо `Scanner` можно использовать более простой и быстрый `BufferedReader`

2020-04-09 12:48 UTC, h31 commented on src/main/java/com/example/utility/Unique.java
> +        } catch (NullPointerException ex) {//ввод с консоли если файл не сущетсвует
NPE - это т.н. unchecked исключение. Лучше предотвращать его, т.е. заранее проверять существование файла

2020-04-09 12:48 UTC, h31 commented on src/main/java/com/example/utility/Unique.java
> +    private StringBuilder dataForOutFile = new StringBuilder();//строки для помещения в файл
Есть ли смысл заранее считывать все данные в память?

2020-04-09 12:48 UTC, h31 commented on src/main/java/com/example/utility/Unique.java
> +        } catch (FileNotFoundException ex) {//исключение, если в названии файла допущена ошибка
В чем разница между "файл не сущетсвует" и "в названии файла допущена ошибка"?

2020-04-09 12:48 UTC, h31 commented on src/main/java/com/example/utility/Unique.java
> +            System.out.print(dataForOutFile);
Обратите внимание на переменную `System.out`, она поможет вам объединить этот код и код для вывода в файл

2020-04-09 12:48 UTC, h31 commented on src/main/java/com/example/utility/Unique.java
> +            if (firstWord.toString().equalsIgnoreCase(allLines.get(i))) {
Не понимаю, зачем мы сравниваем с `firstWord`, если нам достаточно сравнить с предыдущей строкой

2020-04-09 12:48 UTC, h31 commented on src/main/java/com/example/utility/Unique.java
> +    public void equalsIgnoreSomeChars(int countIgnore) {
Можно ли объединить этот метод с предыдущим? Они очень похожи

2020-04-09 12:48 UTC, h31 commented on src/main/java/com/example/utility/Unique.java
> +        HashSet<String> set = new HashSet<>();
Зачем нужен Set?

2020-04-09 12:48 UTC, h31 commented on src/main/java/com/example/utility/Unique.java
> +        for (int i = 0; i < allLines.size(); i++) {
Можно ли решить эту задачу более эффективно? Без вложенного цикла

2020-04-09 12:48 UTC, h31 commented on src/test/java/com/example/utility/UniqueTest.java
> +                stringBuilderTest.toString());
Много раз повторяется `stringBuilderTest.toString()`

2020-04-09 17:28 UTC, h31 requested changes

2020-04-09 17:28 UTC, h31 commented on src/test/java/com/example/utility/UniqueTest.java
> +                        "HelloHELLO\n" +
Почему две строки слились в одну?

2020-04-09 17:28 UTC, h31 commented on src/test/java/com/example/utility/UniqueTest.java
> +        UniqueLauncher.main(new String[]{"-c", "inputForCountString.txt"});
Во-первых, было бы сильно удобнее воспринимать код, если бы ввод и вывод были бы рядом. Попробуйте это организовать.

Во-вторых, в тестах тоже много дублирования. Структурно тесты очень похожи друг на друга, отличаются только константами. Это тоже можно решить. Посмотрите, как в этом может помочь JUnit, либо просто вынесите общий код в отдельные методы

2020-04-09 17:28 UTC, h31 commented on src/test/java/com/example/utility/UniqueTest.java
> +        System.setOut(System.out);
В чем смысл этой строчки?

2020-04-09 17:28 UTC, h31 commented on src/test/java/com/example/utility/UniqueTest.java
> +        assertThrows(FileNotFoundException.class, () -> UniqueLauncher.main(new String[]{"-c", "-o", "outpu123t.txt", "inputForCountString.txt"}));
Т.е. если человек неправильно укажет файл, ему на экран выведется стектрейс? Я думаю, это не очень аккуратно и может напугать человека. Давайте сделаем так, чтобы выводились только "человечные" сообщения об ошибках.

2020-04-09 17:29 UTC, h31 commented on src/test/java/com/example/project/UniqueTest.java
> +    void equalsIgnoreCase() throws IOException {
Да, проверьте, пожалуйста, что поведение вашей программы совпадает с поведением `uniq`

2020-04-09 19:27 UTC, h31 commented
Не могу найти Jar-файл. Не забудьте собрать его

2020-04-10 21:47 UTC, yantimirov-timur commented on src/main/java/com/example/utility/Unique.java
> +    private StringBuilder dataForOutFile = new StringBuilder();//строки для помещения в файл
> Есть ли смысл заранее считывать все данные в память?

Мне кажется что да, потому что может оказаться что выходного файла нет и надо будет вывести обработанные строки в консоль. В любом случае, их надо где-то "собрать".

2020-04-10 22:05 UTC, yantimirov-timur commented on src/main/java/com/example/utility/Unique.java
> +            if (firstWord.toString().equalsIgnoreCase(allLines.get(i))) {
> Не понимаю, зачем мы сравниваем с `firstWord`, если нам достаточно сравнить с предыдущей строкой

В uniq подразумевается, что мы выводим или записываем только первую строку, поэтому я сравниваю с ней.

2020-04-11 19:48 UTC, yantimirov-timur commented on src/main/java/com/example/utility/Unique.java
> +        for (int i = 0; i < allLines.size(); i++) {
> Можно ли решить эту задачу более эффективно? Без вложенного цикла

Не совсем представляю как можно решить более эффективно. Тк нужно каждую строку сравнить со всеми другими.

2024-05-05 08:00 UTC, closed without merging